### ISSUE TITLE
/register endpoint returning 504 Gateway timeout

### ISSUE THREAD

**Issue by vsiguero** [JKHeadley/appy-backend#4]
Hi, I'm using your framework for some testing, and I can't guess what happens with the /register endpoint:

When I give this payload to the body:
```json
{
  "user": {
    "firstName": "Test",
    "lastName": "Tester",
    "email": "test@test.com",
    "role": "Admin",
    "password": "testtest"
  },
  "registerType": "Register"
}
```

The server always returns:

```json
{
"msec":228.90566400438547,"error":"An error occurred GenerateKey.","data":{"isBoom":true,"isServer":true,"output":
{"statusCode":504,"payload":{"statusCode":504,"error":"Gateway Timeout","message":"An error occurred."},"he
aders":{}}}}
```

Keep the good work btw!
Thanks

**Comment by pkmgarcia** [comment]
Hey, I was also having this issue, but I found a way to get around it. The issue is with the value corresponding to "role" in the "user" object contained in the payload. This needs to be a role's "_id", not a role's "name". However, joi validates "role" by comparing it to role "name"s stored in the object constants["USER_ROLES"], which lies in /config.js. You will need to edit /config.js so that joi can compare "role" to role "_id"s instead of role "name"s which then allows the payload to pass role "_id"s.

Specifically, use the GET /roles endpoint to get a list of roles. Replace the values in constants["USER_ROLES"], found in /config.js, with the corresponding role "_id"s.  Then whenever you give the payload,  pass the role "_id" that corresponds to the role you wish to use.

**Comment by JKHeadley** [comment]
Thanks for pointing this out! Also thank you @pkmgarcia for pointing out the workaround.  Somehow this endpoint fell through the cracks during recent development.  @vsiguero, if you pull the most recent code for the registration endpoint your payload should work.  Although @pkmgarcia's work around is a viable option, I would suggest sticking with passing the role's "name" to the endpoint, simply because the use case of this endpoint assumes the user does not have an account, and therefore can not authenticate.  In a working application the user would have to authenticate in order to pass a "GET" to the /roles endpoint, which would make it difficult to access the corresponding role "_Id".
